controller:
  ## AWS region in which this ingress controller will operate
  awsRegion: us-west-1
  ## Container image used for the Ingress Controller
  image:
    repository: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller
    tag: "latest"
    pullPolicy: IfNotPresent

daemonset:
  ## Container image used for the Daemon set
  image:
    repository: registry.opensource.zalan.do/pathfinder/skipper
    tag: "latest"
    pullPolicy: IfNotPresent
  # Resource configuration for limits and requests
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 25m
      memory: 25Mi

## RBAC support
rbac:
  create: false
  serviceAccountName: kube-aws-ingress-controller
