apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kube-aws-ingress-controller.name" . }}-skipper-ingress
  namespace: kube-system
  labels:
    component: ingress
spec:
  selector:
    matchLabels:
      component: ingress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ template "kube-aws-ingress-controller.name" . }}-skipper-ingress
      labels:
        component: ingress
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      hostNetwork: true
      containers:
      - name: {{ template "kube-aws-ingress-controller.name" . }}
        image: "{{ .Values.daemonset.image.repository }}:{{ .Values.daemonset.image.tag }}"
        imagePullPolicy: "{{ .Values.daemonset.image.pullPolicy }}"
        ports:
        - name: ingress-port
          containerPort: 9999
          hostPort: 9999
        args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-address=:9999"
          - "-proxy-preserve-host"
          - "-serve-host-metrics"
          - "-enable-ratelimits"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-kubernetes-https-redirect=true"
        resources:
          limits:
            cpu: {{ .Values.daemonset.resources.limits.cpu }}
            memory: {{ .Values.daemonset.resources.limits.memory }}
          requests:
            cpu: {{ .Values.daemonset.resources.requests.cpu }}
            memory: {{ .Values.daemonset.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /kube-system/healthz
            port: 9999
          initialDelaySeconds: 5
          timeoutSeconds: 5
